/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLiSanPham;

import Menu.MenuAdminUI;
import Object.DanhMucObject;
import Object.SanPhamObject;
import RunProject.ConnectDB;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MD-03092021
 */
public class QuanLySanPhamUI extends javax.swing.JFrame {

    /**
     * Creates new form QuanLySanPhamUI
     */
    ConnectDB connectDB = new ConnectDB();
    private JPanel panel;
    ArrayList<DanhMucObject> listDM = connectDB.dsDanhMuc();
    ArrayList<SanPhamObject> listSP = connectDB.dsSanPham();

    public QuanLySanPhamUI() {
        initComponents();
        setLocationRelativeTo(null);
        loadTable(connectDB.dsSanPham());

        final DefaultComboBoxModel DMModel = (DefaultComboBoxModel) cbDanhMuc.getModel();
        for (DanhMucObject dm : listDM) {
            DMModel.addElement(dm.getTenDanhMuc());
        }
        cbDanhMuc = new JComboBox(DMModel);
        cbDanhMuc.setSelectedIndex(0);
        tbSanPham.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent mouseEvent) {

                int row = tbSanPham.getSelectedRow();
                //int maSanPham = (int) tbSanPham.getModel().getValueAt(row, 0);
                String tenSanPham = (String) tbSanPham.getModel().getValueAt(row, 1);
                int maDanhMuc = (int) tbSanPham.getModel().getValueAt(row, 2);
                String donViTinh = (String) tbSanPham.getModel().getValueAt(row, 3);
                int soLuong = (int) tbSanPham.getModel().getValueAt(row, 4);
                int donGia = (int) tbSanPham.getModel().getValueAt(row, 5);
                String kichCo = (String) tbSanPham.getModel().getValueAt(row, 6);
                String moTa = (String) tbSanPham.getModel().getValueAt(row, 7);
//                tfMaHoaDon.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                XemChiTietSanPham xem = new XemChiTietSanPham(tenSanPham, maDanhMuc, donViTinh, soLuong, donGia, kichCo, moTa, listDM);

                if (mouseEvent.getClickCount() == 2) {
                    xem.setVisible(true);
                    xem.pack();
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnQuayLai = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbDanhMuc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfSoLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfKichCo1 = new javax.swing.JTextField();
        tfTenSanPham = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfDonGia = new javax.swing.JTextField();
        tfDonViTinh = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnTaoMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfMoTa = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnTimKiemSanPham = new javax.swing.JButton();
        tfTimKiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ SẢN PHẨM");

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/back.png"))); // NOI18N
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setText("Số Lượng");

        jLabel3.setText("Mã Danh Mục");

        cbDanhMuc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDanhMucItemStateChanged(evt);
            }
        });

        jLabel2.setText("Tên Sản Phẩm");

        jLabel6.setText("Kích cỡ");

        tfKichCo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKichCo1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Đơn Vị Tính");

        jLabel7.setText("Đơn giá");

        jLabel9.setText("Mô tả");

        tfDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDonGiaActionPerformed(evt);
            }
        });

        tfDonViTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDonViTinhActionPerformed(evt);
            }
        });

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên sản phẩm", "Mã DM", "ĐVT", "Số lượng", "Đơn giá", "Kích cỡ", "Mô tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbSanPham);

        btnXoa.setBackground(new java.awt.Color(188, 210, 112));
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(188, 210, 112));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnTaoMoi.setBackground(new java.awt.Color(188, 210, 112));
        btnTaoMoi.setText("Tạo mới");
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(188, 210, 112));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        tfMoTa.setColumns(20);
        tfMoTa.setRows(5);
        jScrollPane1.setViewportView(tfMoTa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(59, 59, 59))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnThem)
                                        .addGap(78, 78, 78)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnXoa)
                                        .addGap(73, 73, 73)
                                        .addComponent(btnSua)
                                        .addGap(59, 59, 59)
                                        .addComponent(btnTaoMoi))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfKichCo1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfKichCo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tfDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel9)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTaoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3.setAlignmentX(0.0F);

        btnTimKiemSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/search.png"))); // NOI18N
        btnTimKiemSanPham.setAlignmentY(0.0F);
        btnTimKiemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemSanPhamActionPerformed(evt);
            }
        });

        tfTimKiem.setText("TÌM KIẾM");
        tfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimKiemActionPerformed(evt);
            }
        });
        tfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTimKiemKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTimKiemSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnQuayLai)
                .addGap(144, 144, 144)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuayLai)
                    .addComponent(jLabel1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (tfTenSanPham.getText().isEmpty()
                || tfDonGia.getText().isEmpty()
                || tfKichCo1.getText().isEmpty()
                || tfSoLuong.getText().isEmpty()
                || tfDonViTinh.getText().isEmpty()) {
            JOptionPane.showMessageDialog(
                    panel,
                    "Không thể để trống",
                    "Lỗi",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try {
            //int maSanPham;
            String tenSanPham = tfTenSanPham.getText();
            int maDanhMuc = cbDanhMuc.getSelectedIndex() + 1;
            String donViTinh = tfDonViTinh.getText();
            int soLuong = Integer.parseInt(tfSoLuong.getText());
            int donGia = Integer.parseInt(tfDonGia.getText());
            String kichCo = tfKichCo1.getText();
            String moTa = tfMoTa.getText();
            // tenSanPham = tfTenSanPham.getText();
            if (soLuong < 0 || donGia < 0) {
                JOptionPane.showMessageDialog(
                        panel,
                        "số lượng và đơn giá >0",
                        "Lỗi",
                        JOptionPane.INFORMATION_MESSAGE);
                return;

            }

            SanPhamObject x = new SanPhamObject(tenSanPham, maDanhMuc, donViTinh, soLuong, donGia, kichCo, moTa);
            if (connectDB.themSanPham(x) == true) {

                JOptionPane.showMessageDialog(null, "Thêm mới thành công");
                loadTable(connectDB.dsSanPham());
            } else {
                JOptionPane.showMessageDialog(
                        panel,
                        "Thêm thất bại",
                        "Lỗi",
                        JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    panel,
                    "Số lượng và đơn giá là số nguyên ",
                    "Lỗi",
                    JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        // SanPhamObject a=tbSanPham.getSelectedRows(tbSanPham.getSelectedRow());
        int row = tbSanPham.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(
                    panel,
                    "Bạn chưa chọn sản phẩm nào để sửa",
                    "Lỗi",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int maSanPham = (int) tbSanPham.getModel().getValueAt(row, 0);
        String tenSanPham = tfTenSanPham.getText();
        int maDanhMuc = cbDanhMuc.getSelectedIndex() + 1;
        String donViTinh = tfDonViTinh.getText();
        int soLuong = Integer.parseInt(tfSoLuong.getText());
        int donGia = Integer.parseInt(tfDonGia.getText());
        String kichCo = tfKichCo1.getText();
        String moTa = tfMoTa.getText();

        SanPhamObject x = new SanPhamObject(maSanPham, tenSanPham, maDanhMuc, donViTinh, soLuong, donGia, kichCo, moTa);
        if (tfTenSanPham.getText().isEmpty()
                || tfDonGia.getText().isEmpty()
                || tfKichCo1.getText().isEmpty()
                || tfSoLuong.getText().isEmpty()
                || tfDonViTinh.getText().isEmpty()) {
            JOptionPane.showMessageDialog(
                    panel,
                    "Không thể để trống",
                    "Lỗi",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
            //int maSanPham;
            
            // tenSanPham = tfTenSanPham.getText();
            if (soLuong < 0 || donGia < 0) {
                JOptionPane.showMessageDialog(
                        panel,
                        "số lượng và đơn giá >0",
                        "Lỗi",
                        JOptionPane.INFORMATION_MESSAGE);
                return;

            }

            if (connectDB.suaSanPham(x) == true) {

                JOptionPane.showMessageDialog(null, "Sửa  thành công");
                loadTable(connectDB.dsSanPham());
            } else {
                JOptionPane.showMessageDialog(
                        panel,
                        "Sửa thất bại",
                        "Lỗi",
                        JOptionPane.INFORMATION_MESSAGE);
            }

        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row = tbSanPham.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(
                    panel,
                    "Bạn chưa chọn sản phẩm nào để xóa",
                    "Lỗi",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int maSanPham = (int) tbSanPham.getModel().getValueAt(row, 0);
        String tenSanPham = (String) tbSanPham.getModel().getValueAt(row, 1);
        int n = JOptionPane.showConfirmDialog(
                panel,
                "Bạn có chắc chắn muốn xóa " + tenSanPham,
                "Alert",
                JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Xóa thành công");
            connectDB.xoaSanPham(maSanPham);
            loadTable(connectDB.dsSanPham());
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiActionPerformed
        // TODO add your handling code here:
        cbDanhMuc.setSelectedIndex(0);
        tfTenSanPham.setText("");
        tfDonViTinh.setText("");
        tfSoLuong.setText(String.valueOf(""));
        tfDonGia.setText(String.valueOf(""));
        tfKichCo1.setText("");
        tfMoTa.setText("");
    }//GEN-LAST:event_btnTaoMoiActionPerformed

    private void cbDanhMucItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDanhMucItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDanhMucItemStateChanged

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        MenuAdminUI menu = new MenuAdminUI();
        menu.pack();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void tbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMouseClicked
        // TODO add your handling code here:
        int row = tbSanPham.getSelectedRow();
        tfTenSanPham.setText((String) tbSanPham.getModel().getValueAt(row, 1));
        cbDanhMuc.setSelectedIndex(((int) tbSanPham.getModel().getValueAt(row, 2)) - 1);
        tfDonViTinh.setText((String) tbSanPham.getModel().getValueAt(row, 3));
        tfSoLuong.setText( tbSanPham.getModel().getValueAt(row, 4).toString());
        tfDonGia.setText(tbSanPham.getModel().getValueAt(row, 5).toString());
        tfKichCo1.setText( tbSanPham.getModel().getValueAt(row, 6).toString());
        tfMoTa.setText( tbSanPham.getModel().getValueAt(row, 7).toString());
        System.out.println(tbSanPham.getModel().getValueAt(row, 4));

    }//GEN-LAST:event_tbSanPhamMouseClicked

    private void tfDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDonGiaActionPerformed

    private void tfKichCo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKichCo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKichCo1ActionPerformed

    private void tfDonViTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDonViTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDonViTinhActionPerformed

    private void btnTimKiemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemSanPhamActionPerformed
        // TODO add your handling code here:
        tfTimKiem.setText("");
        tfTimKiem.requestFocus(true);

    }//GEN-LAST:event_btnTimKiemSanPhamActionPerformed

    private void tfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimKiemActionPerformed

    private void tfTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTimKiemKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = tfTimKiem.getText();
            if (name.trim().isEmpty()) {
                //loadVolunteers();
                loadTable(connectDB.dsSanPham());
            } else {
                loadTable(connectDB.timKiemSanPham(name));
            }

        }
    }//GEN-LAST:event_tfTimKiemKeyPressed
    private void loadTable(ArrayList<SanPhamObject> listSanPham ) {

        DefaultTableModel tableModel = (DefaultTableModel) tbSanPham.getModel();
        for (int i = tbSanPham.getRowCount() - 1; i >= 0; i--) {
            tableModel.removeRow(i);
        }
        //tableModel.removeRow(ERROR);
        for (SanPhamObject sp : listSanPham) {
            Object[] obj = {sp.getMaSanPham(), sp.getTenSanPham(), sp.getMaDanhMuc(), sp.getDonViTinh(), sp.getSoLuong(), sp.getDonGia(), sp.getKichCo(), sp.getMoTa()};
            tableModel.addRow(obj);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPhamUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPhamUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPhamUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPhamUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySanPhamUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiemSanPham;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbDanhMuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField tfDonGia;
    private javax.swing.JTextField tfDonViTinh;
    private javax.swing.JTextField tfKichCo1;
    private javax.swing.JTextArea tfMoTa;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfTenSanPham;
    private javax.swing.JTextField tfTimKiem;
    // End of variables declaration//GEN-END:variables
}
